name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Build | install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libudev-dev

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run cargo build
        run: cargo build --verbose